//requirejs的配置
require.config({
	baseUrl:"/",
	paths:{
		"template":"lib/arttemplate/template-native",
		"jquery":"lib/jquery/jquery-1.12.4.min",
		"cookie":"lib/jquery_plugins/jquery.cookie",
		"fly":"lib/jquery_plugins/jquery.fly.min",
		"load":"js/loadHeaderFooter",
		"tool":"js/tools",
		"fang":"js/magnifier",
	},
});
